package com.example.cart.entity;

public enum Category {
    JAVA, PHYSICS, CHEMISTRY, MATHEMATICS, SCIENCE, PROGRAMMING, ART, SELF_DEVELOPMENT, WEB_DEVELOPMENT,
    ARTIFICIAL_INTELLIGENCE, MACHINE_LEARNING, DATA_SCIENCE, ANALYTICS, CLOUD_COMPUTING, AWS, GCP, AZURE,
    COMPUTER_SCIENCE, WEB_APPLICATION, ANDROID, MARKETING, ACCOUNTING, SPRING
}
